"""Update nullable constraints for auth related models

Revision ID: 9b817947bbb8
Revises: b6b6de601e4a
Create Date: 2025-06-23 14:04:50.927933+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9b817947bbb8'
down_revision: Union[str, None] = 'b6b6de601e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'access_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('accounts', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('accounts', 'id_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('accounts', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('accounts', 'scope',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('accounts', 'scope',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('accounts', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('accounts', 'id_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('accounts', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('accounts', 'access_token',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
