services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
      target: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: summarize
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:8.0.2
    ports:
      - "6379:6379"
  pgadmin4:
    image: dpage/pgadmin4:9.5.0
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres@postgres.com
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  maildev:
    image: maildev/maildev:2.2.1
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres-data:
  pgadmin-data:
